name: cowk8s
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Kubernetes for workstations and appliances
description: |
  Cokw8s is a small, fast, secure, single node Kubernetes that installs on
  just about any Linux box. Use it for offline development, prototying,

grade: stable
confinement: classic
base: core18

apps:
  cowk8s:
    command: cowk8s.wrapper

parts:
  cowk8s:
    plugin: dump
    build-attributes: [no-patchelf]
    build-packages:
      - make
